// /shared/west-bengal-data.ts
import { PlaceSpec, Hotel } from "./types";

// ===== All Places in West Bengal =====
export const PLACES: PlaceSpec[] = [
  // ===== Kolkata =====
  {
    id: "dumdum-airport",
    name: "Netaji Subhas Chandra Bose International Airport",
    category: "Transport",
    lat: 22.6547,
    lon: 88.4467,
    city: "Kolkata",
    images: ["/media/dumdum-airport.jpg", "/media/dumdum-airport-1.jpg"],
    description:
      "Major international airport serving Kolkata and Eastern India, named after freedom fighter Netaji Subhas Chandra Bose.",
    tips: ["Arrive 2 hours before departure", "Metro and taxi available for city transit"],
    entryFeeINR: "Depends on airline",
    hours: "24 hours",
  },
  
  {
    id: "victoria-memorial",
    name: "Victoria Memorial",
    category: "Heritage",
    lat: 22.5448,
    lon: 88.3426,
    city: "Kolkata",
    images: ["/media/victoria.webp", "/media/victoria-memorial-kolkata.png"],
    description:
      "Iconic marble museum and gardens dedicated to Queen Victoria; blend of British and Mughal elements.",
    tips: ["Best light at golden hour", "Closed Mondays"],
    entryFeeINR: 30,
    hours: "10:00–17:00",
  },
  {
    id: "dakshineswar-temple",
    name: "Dakshineswar Kali Temple",
    category: "Temple",
    lat: 22.6556,
    lon: 88.357,
    city: "Kolkata",
    images: ["/media/dakhineswar.jpg"],
    description:
      "19th-century riverside temple complex dedicated to Goddess Kali on the Hooghly.",
    tips: ["Dress modestly", "Early mornings less crowded"],
    entryFeeINR: "Free",
    hours: "06:00–12:30, 15:00–20:30",
  },

  // ===== Sundarbans =====
  {
    id: "sundarbans",
    name: "Sundarbans Mangroves",
    category: "Nature",
    lat: 21.9497,
    lon: 88.833,
    city: "South 24 Parganas",
    images: ["/media/sundarbans.webp", "/media/sundarbans-tigers.png"],
    description:
      "World’s largest mangrove forest and Royal Bengal Tiger habitat; boat safaris via Gosaba, Godkhali.",
    tips: ["Permits required", "Best Nov–Feb"],
    entryFeeINR: 100,
    hours: "Permits/boat timings",
  },

  // ===== Alipurduar =====
  {
    id: 'jayanti',
    name: 'Jayanti',
    category: 'Nature',
    lat: 26.6172,
    lon: 89.6013,
    city: 'Jayanti',
    images: ['/media/Alipurduar District/Jayant-Riverbed.jpg'],
    description: 'A serene riverside spot along the Jayanti River bordering Bhutan hills, rich in wildlife and scenic beauty.',
    tips: ['Visit Jayanti Mahakal Cave', 'Carry binoculars for birdwatching'],
    entryFeeINR: 'Free',
    hours: 'Open all day'
  },
  {
    id: 'chilapata',
    name: 'Chilapata Wildlife Sanctuary',
    category: 'Wildlife',
    lat: 26.5775,
    lon: 89.4021,
    city: 'Chilapata',
    images: [
      '/media/Alipurduar District/chiltapara.jpg',
      '/media/Alipurduar District/Chilapata.jpg',
      '/media/Alipurduar District/River-Beside-Chilapata-Jungle-Camp.jpg'
    ],
    description: 'Dense forest corridor between Buxa and Jaldapara, home to elephants, rhinos, leopards, and rare orchids.',
    tips: ['Wildlife safari from Mendabari watchtower', 'Best Nov–Mar'],
    entryFeeINR: 100,
    hours: '06:00–17:00'
  },
  {
    id: 'raimatang',
    name: 'Raimatang',
    category: 'Village',
    lat: 26.766079,
    lon: 89.503765,
    city: 'Raimatang',
    images: [
      '/media/Alipurduar District/raim.jpg',
      '/media/Alipurduar District/rai.jpg',
      '/media/Alipurduar District/1Raimatang.jpg',
      '/media/Alipurduar District/raimatang_1.webp'
    ],
    description: 'A riverside village in Buxa Reserve, known for treks, forest beauty, and rock climbing opportunities.',
    tips: ['Great base for Adma trek', 'Minimal tourist facilities—plan ahead'],
    entryFeeINR: 'Free',
    hours: 'Open all day'
  },
  {
    id: 'jaigaon',
    name: 'Jaigaon',
    category: 'Town',
    lat: 26.8470,
    lon: 89.3755,
    city: 'Jaigaon',
    images: [
      '/media/Alipurduar District/jai.jpg',
      '/media/Alipurduar District/jaigaon.jpg'
    ],
    description: 'Border town at Bhutan’s Phuentsholing gate, buzzing with trade and cultural exchanges.',
    tips: ['Great for cross-border shopping', 'Try local Bhutanese food nearby'],
    entryFeeINR: 'Free',
    hours: 'Open all day'
  },
  {
    id: 'totopara',
    name: 'Totopara',
    category: 'Village',
    lat: 26.8342,
    lon: 89.3627,
    city: 'Totopara',
    images: [
      '/media/Alipurduar District/toto.jpg',
      '/media/Alipurduar District/toto-para.webp'
    ],
    description: 'Home of the unique Toto tribe with distinct culture and traditions, preserved over centuries.',
    tips: ['Respect local customs', 'Engage with local handicrafts'],
    entryFeeINR: 'Free',
    hours: 'Open all day'
  },
  {
    id: 'rajabhatkhawa',
    name: 'Rajabhatkhawa',
    category: 'Nature',
    lat: 26.6166,
    lon: 89.5483,
    city: 'Rajabhatkhawa',
    images: [
      '/media/Alipurduar District/Rajabhat.jpg',
      '/media/Alipurduar District/Rajabhatkhawa.jpg'
    ],
    description: 'Gateway town to Buxa Tiger Reserve, known for birdwatching, trekking, and safari permits.',
    tips: ['Carry ID for permits', 'Wildlife sightings best in early morning'],
    entryFeeINR: 'Permit charges apply',
    hours: '06:00–17:00'
  },
  {
    id: 'buxa-tiger-reserve',
    name: 'Buxa Tiger Reserve',
    category: 'Wildlife',
    lat: 26.6276,
    lon: 89.5661,
    city: 'Buxa',
    images: [
      '/media/Alipurduar District/Buxa.jpg',
      '/media/Alipurduar District/Buxa.webp'
    ],
    description: '760 sq km reserve rich in biodiversity—tigers, elephants, leopards, and rare birds.',
    tips: ['Safari bookings in advance', 'Best Nov–Mar'],
    entryFeeINR: 150,
    hours: '06:00–17:00'
  },
  {
    id: 'jaldapara',
    name: 'Jaldapara National Park',
    category: 'Wildlife',
    lat: 26.6882,
    lon: 89.2755,
    city: 'Madarihat',
    images: [
      '/media/Alipurduar District/jaldapara-wildlife.jpg',
      '/media/Alipurduar District/Jaldpara-Tourism.jpg'
    ],
    description: 'National park famous for Indian one-horned rhinos, elephants, and Bengal florican.',
    tips: ['Book elephant safari early', 'Excellent for birdwatching'],
    entryFeeINR: 100,
    hours: '06:00–17:00'
  },


  // ===== Bankura =====
{
  id: "bishnupur-terracotta",
  name: "Bishnupur Terracotta Temples",
  category: "Heritage",
  lat: 23.0738,
  lon: 87.3199,
  city: "Bishnupur",
  images: ["/media/Bankura/bishnupur-terracotta.jpg",'/media/Bankura/bishnupur.jpg'],
  description: "Famed terracotta temples (17th–18th c.) with intricate panels depicting epics and local life.",
  tips: ["Hire a local guide", "Carry water, summers are hot"],
  entryFeeINR: 50,
  hours: "Sunrise–Sunset",
},
{
  id: "susunia-hill",
  name: "Susunia Hill",
  category: "Nature",
  lat: 23.4000,
  lon: 86.9833,
  city: "Bankura",
  images: ["/media/Bankura/Susunia-Hills.jpg",'/media/Bankura/su.jpg'],
  description: "A hill famous for rock climbing, trekking, natural springs, and ancient fossils.",
  tips: ["Carry trekking shoes", "Avoid monsoon season"],
  entryFeeINR: "Free",
  hours: "Open all day",
},
{
  id: "joyrambati",
  name: "Joyrambati",
  category: "Pilgrimage",
  lat: 22.9230,
  lon: 87.6100,
  city: "Bankura",
  images: ["/media/Bankura/jo.jpg",'/media/Bankura/joy.jpg'],
  description: "Birthplace of Holy Mother Sarada Devi, with serene temple surroundings.",
  tips: ["Maintain silence inside temple", "Best in morning hours"],
  entryFeeINR: "Free",
  hours: "05:00–20:00",
},
{
  id: "kangsabati-dam",
  name: "Kangsabati Dam",
  category: "Nature",
  lat: 22.96393,
  lon: 86.78895,
  city: "Bankura",
  images: ["/media/Bankura/kangsabati-Dam4.webp", '/media/Bankura/kangsabati-Dam3-1.webp'],
  description: "Scenic reservoir surrounded by hills, ideal for picnics, photography, and sunset views.",
  tips: ["Evening views are best", "Avoid monsoon for safety"],
  entryFeeINR: "Free",
  hours: "Open all day",
},
{
  id: "garh-panchkot",
  name: "Garh Panchkot",
  category: "Heritage",
  lat: 23.5977,
  lon: 86.77291,
  city: "Bankura",
  images: ["/media/Bankura/garhpanchkot-eco-tourism.jpg", '/media/Bankura/Ghar Panchkot.jpg', '/media/Bankura/Generic-6-5.jpg'],
  description: "Ruins of the 16th-century fort of the Panchkot kings, set amidst picturesque hills.",
  tips: ["Good for photography", "Combine visit with Panchet Dam"],
  entryFeeINR: "Free",
  hours: "Open all day",
},
{
  id: "jhilimili",
  name: "Jhilimili",
  category: "Nature",
  lat: 22.8167,
  lon: 86.6167,
  city: "Bankura",
  images: ["/media/Bankura/images.jpeg",'/media/Bankura/Jhilimili-without-watermark-1.webp','/media/Bankura/Rimil-Lodge-Jhilimili.webp','/media/Bankura/images (1).jpeg'],
  description: "A forested hill area known as the 'Darjeeling of Bankura', perfect for nature lovers.",
  tips: ["Best during winter", "Carry water and snacks"],
  entryFeeINR: "Free",
  hours: "Open all day",
},
  

  // ===== Darjeeling =====
  {
    id: "tiger-hill",
    name: "Tiger Hill",
    category: "Hillstation",
    lat: 27.029,
    lon: 88.2655,
    city: "Darjeeling",
    images: ["/media/tiger-hill-sunrise.png"],
    description:
      "Famous sunrise viewpoint offering a panoramic view of Mount Kanchenjunga and Everest on clear days.",
    tips: ["Arrive early before sunrise", "Carry warm clothes"],
    entryFeeINR: "Free",
    hours: "04:00–18:00",
  },
  {
    id: "batasia-loop",
    name: "Batasia Loop",
    category: "Heritage",
    lat: 27.0165,
    lon: 88.2622,
    city: "Darjeeling",
    images: [
      "/media/Darjeeling-toy-train-in-Batasia-loop.jpg",
      "/media/bata.webp",
    ],
    description:
      "Iconic spiral railway loop with a war memorial and gardens, part of the UNESCO Darjeeling Himalayan Railway.",
    tips: ["Best when toy train passes", "Great photography spot"],
    entryFeeINR: 20,
    hours: "Sunrise–Sunset",
  },

  // ===== Digha =====
  {
    id: "new-digha-beach",
    name: "New Digha Beach",
    category: "Beach",
    lat: 21.6266,
    lon: 87.5183,
    city: "Digha",
    images: ["/media/digha/digha-beach-bay-of-bengal.png"],
    description:
      "Popular beach destination in West Bengal with wide sandy shores, sunrise views, and seafood stalls.",
    tips: ["Avoid weekends for less crowd", "Best early morning"],
    entryFeeINR: "Free",
    hours: "Open all day",
  },

  // Birbhum District (central)
  {
    id: "birbhum-district",
    name: "Birbhum District (approx. center)",
    category: "Town",
    lat: 24.000000,
    lon: 87.583330,
    city: "Birbhum",
    images: [], // optional
    description: "Administrative district of West Bengal, known as the Land of Red Soil.",
    tips: [],
    entryFeeINR: "N/A",
    hours: "Open all day",
  },
  // Tarapith
  {
    id: "tarapith",
    name: "Tarapith Temple Town",
    category: "Pilgrimage",
    lat: 24.1100,
    lon: 87.8000,
    city: "Birbhum",
    images: [], // you can add images
    description:
      "Famous Tantric pilgrimage site dedicated to Maa Tara, known for the Tarapith Temple and Bamakhepa’s ashram at the cremation grounds.",
    tips: ["Respect local customs", "Best to visit early to avoid crowds"],
    entryFeeINR: "Free",
    hours: "All day",
  },
  {
    id: "visva-bharati",
    name: "Visva-Bharati University",
    category: "Heritage",
    lat: 23.6776,
    lon: 87.686,
    city: "Shantiniketan",
    images: ["/media/shantiniketan-university.png", "/media/santi.png"],
    description:
      "Founded by Rabindranath Tagore, it is a center of culture, arts, and education with historic significance.",
    tips: ["Check seasonal festivals", "Explore Tagore’s ashram nearby"],
    entryFeeINR: 30,
    hours: "10:00–17:00",
  },
  // ===== Places in Cooch Behar =====
  {
    id: "cooch-behar-palace",
    name: "Cooch Behar Palace",
    category: "Heritage",
    lat: 26.32694,
    lon: 89.43861,
    city: "Cooch Behar",
    images: ['/media/Cooch-behar/c-palace.jpg', '/media/Cooch-behar/COOCHBEHAR-3-1024x768-1.webp','/media/cooch-behar-palace.png'],
    description: "Elegant Italian Renaissance-style palace and museum, former royal residence of Koch dynasty.",
    tips: ["Best for photography", "Check museum timings"],
    entryFeeINR: "Varies",
    hours: "Typically 10:00–17:00",
  },
  {
    id: "madan-mohan-temple",
    name: "Madan Mohan Temple",
    category: "Temple",
    lat: 26.32024,
    lon: 89.44549,
    city: "Cooch Behar",
    images: ['media/Cooch-behar/madan-mohan-temple.jpg','/media/Cooch-behar/Madan_Mohan_Bari_Cooch_Behar.jpg'],
    description: "White temple dedicated to Lord Madan Mohan and other deities; center of Rash Yatra and Mela.",
    tips: ["Attend during Rash Yatra", "Moderate crowd post-festival"],
    entryFeeINR: "Free",
    hours: "All day",
  },
  {
    id: "baneswar-shiva-temple",
    name: "Baneswar Shiva Temple",
    category: "Temple",
    lat: 26.399063,
    lon: 89.497535,
    city: "Baneswar",
    images: ['/media/Cooch-behar/Baneshwar_Shiva_temple.jpg','/media/Cooch-behar/BS tempel.webp'],
    description: "Ancient Shiva temple with Shivalinga 10 ft below plinth and pond with tortoises (~10 km from city).",
    tips: ["“Maha Shivaratri is special", "Also visit the tortoise pond"],
    entryFeeINR: "Free",
    hours: "All day",
  },
  {
    id: "gosanimari-rajpat",
    name: "Gosanimari Rajpat",
    category: "Archaeological",
    lat: 26.032,
    lon: 89.484,
    city: "Gosanimari",
    images: ['/media/Cooch-behar/gosanimari.jpg','/media/Cooch-behar/gosa.jpg','/media/Cooch-behar/rajpat.jpg'],
    description: "Ruins of Kamatapur’s Rajpat fort, earthen walls and archaeological remains.",
    tips: ["Wear comfortable shoes", "Visit with guide if possible"],
    entryFeeINR: "Free",
    hours: "All day",
  },
  {
    id: "siddheswari-kali-bari",
    name: "Siddheswari Kali Bari",
    category: "Temple",
    lat: 26.32419, // estimated close to Cooch Behar center
    lon: 89.45100,
    city: "Cooch Behar",
    images: ['/media/Cooch-behar/ksp_8769-2.jpg','/media/Cooch-behar/kalibari.jpg'],
    description: "Temple built in 1830 by Maharaja Harendra Narayan dedicated to Goddess Siddheswari (~11 km from city).",
    tips: ["Combine with Baneswar visiting", "Peaceful atmosphere"],
    entryFeeINR: "Free",
    hours: "All day",
  },
  {
    id: "patlakhawa-forest",
    name: "Patlakhawa Forest",
    category: "Nature",
    lat: 26.4536,
    lon: 89.4725,
    images: ['/media/Cooch-behar/Patlakhawa Forest.jpeg','/media/Cooch-behar/palakkad.jpg'],
    city: "Patlakhawa",
    description: "Forest area home to elephants, deer, peacocks, and other wildlife.",
    entryFeeINR: "20",
    hours: "Sunrise – Sunset",
  },
];

// ===== All Hotels in West Bengal =====
export const HOTELS: Hotel[] = [
  // Kolkata
  {
    id: "taj-bengal",
    name: "Taj Bengal",
    lat: 22.5404,
    lon: 88.345,
    rating: 4.7,
    priceBand: "Premium",
    nearPlaceId: "victoria-memorial",
    city: "Kolkata",
  },
  {
    id: "park-kolkata",
    name: "The Park Kolkata",
    lat: 22.5535,
    lon: 88.3528,
    rating: 4.3,
    priceBand: "Mid",
    nearPlaceId: "victoria-memorial",
    city: "Kolkata",
  },

  // Sundarbans (none yet)

  // Alipurduar
  {
    id: 'jayanti-resort',
    name: 'Jayanti River View Lodge',
    lat: 26.6165,
    lon: 89.6001,
    rating: 4.1,
    priceBand: 'Budget',
    nearPlaceId: 'jayanti',
    city: 'Jayanti'
  },
  {
    id: 'chilapata-lodge',
    name: 'Mendabari Jungle Camp',
    lat: 26.5790,
    lon: 89.4040,
    rating: 4.4,
    priceBand: 'Mid',
    nearPlaceId: 'chilapata',
    city: 'Chilapata'
  },
  {
    id: 'raimatang-eco',
    name: 'Raimatang Eco Stay',
    lat: 26.6125,
    lon: 89.6730,
    rating: 4.0,
    priceBand: 'Budget',
    nearPlaceId: 'raimatang',
    city: 'Raimatang'
  },
  {
    id: 'jaigaon-inn',
    name: 'Hotel Druk Jaigaon',
    lat: 26.8465,
    lon: 89.3742,
    rating: 4.2,
    priceBand: 'Mid',
    nearPlaceId: 'jaigaon',
    city: 'Jaigaon'
  },
  {
    id: 'totopara-camp',
    name: 'Totopara Tribal Homestay',
    lat: 26.8335,
    lon: 89.3635,
    rating: 4.3,
    priceBand: 'Budget',
    nearPlaceId: 'totopara',
    city: 'Totopara'
  },
  {
    id: 'rajabhatkhawa-hotel',
    name: 'Rajabhatkhawa Forest Lodge',
    lat: 26.6150,
    lon: 89.5470,
    rating: 4.1,
    priceBand: 'Budget',
    nearPlaceId: 'rajabhatkhawa',
    city: 'Rajabhatkhawa'
  },
  {
    id: 'buxa-lodge',
    name: 'Buxa Jungle Lodge',
    lat: 26.6280,
    lon: 89.5650,
    rating: 4.5,
    priceBand: 'Mid',
    nearPlaceId: 'buxa-tiger-reserve',
    city: 'Buxa'
  },
  {
    id: 'jaldapara-safari',
    name: 'Jaldapara Safari Lodge',
    lat: 26.6890,
    lon: 89.2770,
    rating: 4.6,
    priceBand: 'Premium',
    nearPlaceId: 'jaldapara',
    city: 'Madarihat'
  },

  // Bankura
  {
    id: 'green-palace-guest',
    name: 'Green Palace Guest House',
    lat: 23.2375,
    lon: 87.0719,
    rating: 4.8,
    priceBand: 'Budget',
    nearPlaceId: 'susunia-hill',
    city: 'Bankura'
  },
  {
    id: 'maa-laxmi-lodge',
    name: 'Hotel O Maa Laxmi Lodge',
    lat: 23.2324,
    lon: 87.0782,
    rating: 3.4,
    priceBand: 'Budget',
    nearPlaceId: 'susunia-hill',
    city: 'Bankura'
  },
  {
    id: 'anticlock-resort',
    name: 'Anticlock Suites & Resort',
    lat: 23.2850,
    lon: 87.0610,
    rating: 4.5,
    priceBand: 'Premium',
    nearPlaceId: 'susunia-hill',
    city: 'Bankura'
  },
  {
    id: 'hotel-olivia',
    name: 'Hotel Olivia and Resort',
    lat: 23.0659,
    lon: 87.3214,
    rating: 3.7,
    priceBand: 'Mid',
    nearPlaceId: 'bishnupur-terracotta',
    city: 'Bishnupur'
  },
  {
    id: 'hotel-annapurna',
    name: 'Hotel Annapurna Bishnupur',
    lat: 23.0732,
    lon: 87.3220,
    rating: 4.0,
    priceBand: 'Budget',
    nearPlaceId: 'bishnupur-terracotta',
    city: 'Bishnupur'
  },
  {
    id: 'monalisa-lodge',
    name: 'Monalisa Lodge Bishnupur',
    lat: 23.0739,
    lon: 87.3232,
    rating: 3.9,
    priceBand: 'Budget',
    nearPlaceId: 'bishnupur-terracotta',
    city: 'Bishnupur'
  },
  {
    id: 'sonar-bangla-joypur',
    name: 'Hotel Sonar Bangla Joypur Forest',
    lat: 23.0545,
    lon: 87.3060,
    rating: 4.2,
    priceBand: 'Mid',
    nearPlaceId: 'bishnupur-terracotta',
    city: 'Bishnupur'
  },
  {
    id: "bishnupur-guest",
    name: "Bishnupur Heritage Stay",
    lat: 23.072,
    lon: 87.324,
    rating: 4.2,
    priceBand: "Budget",
    nearPlaceId: "bishnupur-terracotta",
    city: "Bishnupur"
  },

  // Darjeeling
  {
    id: "mayfair-darjeeling",
    name: "Mayfair Darjeeling",
    lat: 27.0418,
    lon: 88.2627,
    rating: 4.6,
    priceBand: "Premium",
    nearPlaceId: "tiger-hill",
    city: "Darjeeling",
  },

  // Digha
  {
    id: "sea-hawk-digha",
    name: "Hotel Sea Hawk",
    lat: 21.627,
    lon: 87.519,
    rating: 4.2,
    priceBand: "Mid",
    nearPlaceId: "new-digha-beach",
    city: "Digha",
  },

  // Shantiniketan
  {
    id: "camellia-resort",
    name: "Camellia Resort Shantiniketan",
    lat: 23.678,
    lon: 87.689,
    rating: 4.3,
    priceBand: "Mid",
    nearPlaceId: "visva-bharati",
    city: "Shantiniketan",
  },
  {
    id: "camellia-resort",
    name: "Camellia Resort Shantiniketan",
    lat: 23.678,
    lon: 87.689,
    rating: 4.3,
    priceBand: "Mid",
    nearPlaceId: "visva-bharati",
    city: "Shantiniketan",
  },
  {
    id: "tarapith-inn",
  name: "Hotel Tara Inn",
    lat: 24.1090, // approximate
    lon: 87.8010,
     rating: 4.0,
    priceBand: "Budget",
    nearPlaceId: "tarapith",
    city: "Tarapith",
   },
   {
    id: "sonar-bangla-tarapith",
    name: "Hotel Sonar Bangla – Tarapith",
    lat: 24.1085,
    lon: 87.7975,
    rating: 3.9,
    priceBand: "Mid",
    nearPlaceId: "tarapith",
    city: "Tarapith",
  },
  {
    id: "rajdeep-guest-house",
    name: "Rajdeep Guest House",
    lat: 24.1090,
    lon: 87.7980,
    rating: 4.2,
    priceBand: "Budget",
    nearPlaceId: "tarapith",
    city: "Tarapith",
  },
  {
    id: "hotel-royal-city",
    name: "Hotel Royal City",
    lat: 26.3230,
    lon: 89.4490,
    rating: 3.1,
    priceBand: "Budget",
    nearPlaceId: "cooch-behar-palace",
    city: "Cooch Behar",
  },
  {
    id: "hotel-heritage-kanta",
    name: "Kanta Heritage Hotel",
    lat: 26.3245,
    lon: 89.4515,
    rating: 3.5,
    priceBand: "Mid",
    nearPlaceId: "cooch-behar-palace",
    city: "Cooch Behar",
  },
  {
    id: "hotel-debdutta",
    name: "Hotel Debdutta",
    lat: 26.3250,
    lon: 89.4520,
    rating: 3.5,
    priceBand: "Mid",
    nearPlaceId: "cooch-behar-palace",
    city: "Cooch Behar",
  },
  {
    id: "hotel-akash-ganga",
    name: "Hotel Akash Ganga",
    lat: 26.3255,
    lon: 89.4530,
    rating: 3.8,
    priceBand: "Mid",
    nearPlaceId: "cooch-behar-palace",
    city: "Cooch Behar",
  },
  {
    id: "capital-residency",
    name: "Capital Residency",
    lat: 26.3260,
    lon: 89.4505,
    rating: 3.9,
    priceBand: "Mid",
    nearPlaceId: "cooch-behar-palace",
    city: "Cooch Behar",
  },
  {
    id: "hotel-mayur",
    name: "Hotel Mayur",
    lat: 26.3280,
    lon: 89.4480,
    rating: 3.2,
    priceBand: "Mid",
    nearPlaceId: "new-cooch-behar-station",
    city: "Cooch Behar",
  },
  {
    id: "hotel-jonaki-restaurant",
    name: "Hotel Jonaki & Family Restaurant",
    lat: 26.3275,
    lon: 89.4475,
    rating: 3.7,
    priceBand: "Budget",
    nearPlaceId: "new-cooch-behar-station",
    city: "Cooch Behar",
  },
  {
    id: "maharani-palace",
    name: "Maharani Palace",
    lat: 26.3270,
    lon: 89.4495,
    rating: 1.9,
    priceBand: "Budget",
    nearPlaceId: "new-cooch-behar-station",
    city: "Cooch Behar",
  },

  // Rural areas of the district
  {
    id: "baneswar-area-stay",
    name: "Baneswar Area Hotel",
    lat: 26.3990,
    lon: 89.4975,
    rating: 4.0, // estimated
    priceBand: "Budget",
    nearPlaceId: "baneswar-shiva-temple",
    city: "Baneswar",
  },
  {
    id: "shree-jee-emporium",
    name: "Shree Jee Emporium",
    lat: 26.3242,
    lon: 89.4508,
    rating: 4.0,
    priceBand: "Mid",
    nearPlaceId: "cooch-behar-palace",
    city: "Cooch Behar",
  },
  {
    id: "tripti-hotel",
    name: "Tripti Hotel",
    lat: 26.3240,
    lon: 89.4510,
    rating: 3.5,
    priceBand: "Budget",
    nearPlaceId: "cooch-behar-palace",
    city: "Cooch Behar",
  },
  {
    id: "white-house-hotel",
    name: "White House Hotel",
    lat: 26.3238,
    lon: 89.4512,
    rating: 3.0,
    priceBand: "Budget",
    nearPlaceId: "cooch-behar-palace",
    city: "Cooch Behar",
  },
  {
    id: "yuvraj-hotel",
    name: "Yuvraj Hotel",
    lat: 26.3235,
    lon: 89.4515,
    rating: 3.5,
    priceBand: "Budget",
    nearPlaceId: "cooch-behar-palace",
    city: "Cooch Behar",
  },
  
];