// /shared/west-bengal-data.ts
import { PlaceSpec, Hotel } from "./types";

// ===== All Places in West Bengal =====
export const PLACES: PlaceSpec[] = [
  // ===== Kolkata =====
  {
    id: "dumdum-airport",
    name: "Netaji Subhas Chandra Bose International Airport",
    category: "Transport",
    lat: 22.6547,
    lon: 88.4467,
    city: "Kolkata",
    images: ["/media/dumdum-airport.jpg", "/media/dumdum-airport-1.jpg"],
    description:
      "Major international airport serving Kolkata and Eastern India, named after freedom fighter Netaji Subhas Chandra Bose.",
    tips: ["Arrive 2 hours before departure", "Metro and taxi available for city transit"],
    entryFeeINR: "Depends on airline",
    hours: "24 hours",
    // isImportant: true,
  },
  
  {
    id: "victoria-memorial",
    name: "Victoria Memorial",
    category: "Heritage",
    lat: 22.5448,
    lon: 88.3426,
    city: "Kolkata",
    images: ["/media/victoria.webp", "/media/victoria-memorial-kolkata.png"],
    description:
      "Iconic marble museum and gardens dedicated to Queen Victoria; blend of British and Mughal elements.",
    tips: ["Best light at golden hour", "Closed Mondays"],
    entryFeeINR: 30,
    hours: "10:00–17:00",
  },
  {
    id: "dakshineswar-temple",
    name: "Dakshineswar Kali Temple",
    category: "Temple",
    lat: 22.6556,
    lon: 88.357,
    city: "Kolkata",
    images: ["/media/dakhineswar.jpg"],
    description:
      "19th-century riverside temple complex dedicated to Goddess Kali on the Hooghly.",
    tips: ["Dress modestly", "Early mornings less crowded"],
    entryFeeINR: "Free",
    hours: "06:00–12:30, 15:00–20:30",
  },

  // ===== Sundarbans =====
  {
    id: "sundarbans",
    name: "Sundarbans Mangroves",
    category: "Nature",
    lat: 21.9497,
    lon: 88.833,
    city: "South 24 Parganas",
    images: ["/media/sundarbans.webp", "/media/sundarbans-tigers.png"],
    description:
      "World’s largest mangrove forest and Royal Bengal Tiger habitat; boat safaris via Gosaba, Godkhali.",
    tips: ["Permits required", "Best Nov–Feb"],
    entryFeeINR: 100,
    hours: "Permits/boat timings",
  },

  // ===== Alipurduar =====
  {
    id: 'jayanti',
    name: 'Jayanti',
    category: 'Nature',
    lat: 26.6172,
    lon: 89.6013,
    city: 'Jayanti',
    images: ['/media/Alipurduar District/Jayant-Riverbed.jpg'],
    description: 'A serene riverside spot along the Jayanti River bordering Bhutan hills, rich in wildlife and scenic beauty.',
    tips: ['Visit Jayanti Mahakal Cave', 'Carry binoculars for birdwatching'],
    entryFeeINR: 'Free',
    hours: 'Open all day'
  },
  {
    id: 'chilapata',
    name: 'Chilapata Wildlife Sanctuary',
    category: 'Wildlife',
    lat: 26.5775,
    lon: 89.4021,
    city: 'Chilapata',
    images: [
      '/media/Alipurduar District/chiltapara.jpg',
      '/media/Alipurduar District/Chilapata.jpg',
      '/media/Alipurduar District/River-Beside-Chilapata-Jungle-Camp.jpg'
    ],
    description: 'Dense forest corridor between Buxa and Jaldapara, home to elephants, rhinos, leopards, and rare orchids.',
    tips: ['Wildlife safari from Mendabari watchtower', 'Best Nov–Mar'],
    entryFeeINR: 100,
    hours: '06:00–17:00'
  },
  {
    id: 'raimatang',
    name: 'Raimatang',
    category: 'Village',
    lat: 26.766079,
    lon: 89.503765,
    city: 'Raimatang',
    images: [
      '/media/Alipurduar District/raim.jpg',
      '/media/Alipurduar District/rai.jpg',
      '/media/Alipurduar District/1Raimatang.jpg',
      '/media/Alipurduar District/raimatang_1.webp'
    ],
    description: 'A riverside village in Buxa Reserve, known for treks, forest beauty, and rock climbing opportunities.',
    tips: ['Great base for Adma trek', 'Minimal tourist facilities—plan ahead'],
    entryFeeINR: 'Free',
    hours: 'Open all day'
  },
  {
    id: 'jaigaon',
    name: 'Jaigaon',
    category: 'Town',
    lat: 26.8470,
    lon: 89.3755,
    city: 'Jaigaon',
    images: [
      '/media/Alipurduar District/jai.jpg',
      '/media/Alipurduar District/jaigaon.jpg'
    ],
    description: 'Border town at Bhutan’s Phuentsholing gate, buzzing with trade and cultural exchanges.',
    tips: ['Great for cross-border shopping', 'Try local Bhutanese food nearby'],
    entryFeeINR: 'Free',
    hours: 'Open all day'
  },
  {
    id: 'totopara',
    name: 'Totopara',
    category: 'Village',
    lat: 26.8342,
    lon: 89.3627,
    city: 'Totopara',
    images: [
      '/media/Alipurduar District/toto.jpg',
      '/media/Alipurduar District/toto-para.webp'
    ],
    description: 'Home of the unique Toto tribe with distinct culture and traditions, preserved over centuries.',
    tips: ['Respect local customs', 'Engage with local handicrafts'],
    entryFeeINR: 'Free',
    hours: 'Open all day'
  },
  {
    id: 'rajabhatkhawa',
    name: 'Rajabhatkhawa',
    category: 'Nature',
    lat: 26.6166,
    lon: 89.5483,
    city: 'Rajabhatkhawa',
    images: [
      '/media/Alipurduar District/Rajabhat.jpg',
      '/media/Alipurduar District/Rajabhatkhawa.jpg'
    ],
    description: 'Gateway town to Buxa Tiger Reserve, known for birdwatching, trekking, and safari permits.',
    tips: ['Carry ID for permits', 'Wildlife sightings best in early morning'],
    entryFeeINR: 'Permit charges apply',
    hours: '06:00–17:00'
  },
  {
    id: 'buxa-tiger-reserve',
    name: 'Buxa Tiger Reserve',
    category: 'Wildlife',
    lat: 26.6276,
    lon: 89.5661,
    city: 'Buxa',
    images: [
      '/media/Alipurduar District/Buxa.jpg',
      '/media/Alipurduar District/Buxa.webp'
    ],
    description: '760 sq km reserve rich in biodiversity—tigers, elephants, leopards, and rare birds.',
    tips: ['Safari bookings in advance', 'Best Nov–Mar'],
    entryFeeINR: 150,
    hours: '06:00–17:00'
  },
  {
    id: 'jaldapara',
    name: 'Jaldapara National Park',
    category: 'Wildlife',
    lat: 26.6882,
    lon: 89.2755,
    city: 'Madarihat',
    images: [
      '/media/Alipurduar District/jaldapara-wildlife.jpg',
      '/media/Alipurduar District/Jaldpara-Tourism.jpg'
    ],
    description: 'National park famous for Indian one-horned rhinos, elephants, and Bengal florican.',
    tips: ['Book elephant safari early', 'Excellent for birdwatching'],
    entryFeeINR: 100,
    hours: '06:00–17:00'
  },


  // ===== Bankura =====
{
  id: "bishnupur-terracotta",
  name: "Bishnupur Terracotta Temples",
  category: "Heritage",
  lat: 23.0738,
  lon: 87.3199,
  city: "Bishnupur",
  images: ["/media/Bankura/bishnupur-terracotta.jpg",'/media/Bankura/bishnupur.jpg'],
  description: "Famed terracotta temples (17th–18th c.) with intricate panels depicting epics and local life.",
  tips: ["Hire a local guide", "Carry water, summers are hot"],
  entryFeeINR: 50,
  hours: "Sunrise–Sunset",
},
{
  id: "susunia-hill",
  name: "Susunia Hill",
  category: "Nature",
  lat: 23.4000,
  lon: 86.9833,
  city: "Bankura",
  images: ["/media/Bankura/Susunia-Hills.jpg",'/media/Bankura/su.jpg'],
  description: "A hill famous for rock climbing, trekking, natural springs, and ancient fossils.",
  tips: ["Carry trekking shoes", "Avoid monsoon season"],
  entryFeeINR: "Free",
  hours: "Open all day",
},
{
  id: "joyrambati",
  name: "Joyrambati",
  category: "Pilgrimage",
  lat: 22.9230,
  lon: 87.6100,
  city: "Bankura",
  images: ["/media/Bankura/jo.jpg",'/media/Bankura/joy.jpg'],
  description: "Birthplace of Holy Mother Sarada Devi, with serene temple surroundings.",
  tips: ["Maintain silence inside temple", "Best in morning hours"],
  entryFeeINR: "Free",
  hours: "05:00–20:00",
},
{
  id: "kangsabati-dam",
  name: "Kangsabati Dam",
  category: "Nature",
  lat: 22.96393,
  lon: 86.78895,
  city: "Bankura",
  images: ["/media/Bankura/kangsabati-Dam4.webp", '/media/Bankura/kangsabati-Dam3-1.webp'],
  description: "Scenic reservoir surrounded by hills, ideal for picnics, photography, and sunset views.",
  tips: ["Evening views are best", "Avoid monsoon for safety"],
  entryFeeINR: "Free",
  hours: "Open all day",
},
{
  id: "garh-panchkot",
  name: "Garh Panchkot",
  category: "Heritage",
  lat: 23.5977,
  lon: 86.77291,
  city: "Bankura",
  images: ["/media/Bankura/garhpanchkot-eco-tourism.jpg", '/media/Bankura/Ghar Panchkot.jpg', '/media/Bankura/Generic-6-5.jpg'],
  description: "Ruins of the 16th-century fort of the Panchkot kings, set amidst picturesque hills.",
  tips: ["Good for photography", "Combine visit with Panchet Dam"],
  entryFeeINR: "Free",
  hours: "Open all day",
},
{
  id: "jhilimili",
  name: "Jhilimili",
  category: "Nature",
  lat: 22.8167,
  lon: 86.6167,
  city: "Bankura",
  images: ["/media/Bankura/images.jpeg",'/media/Bankura/Jhilimili-without-watermark-1.webp','/media/Bankura/Rimil-Lodge-Jhilimili.webp','/media/Bankura/images (1).jpeg'],
  description: "A forested hill area known as the 'Darjeeling of Bankura', perfect for nature lovers.",
  tips: ["Best during winter", "Carry water and snacks"],
  entryFeeINR: "Free",
  hours: "Open all day",
},
  

  // ===== Darjeeling =====
  {
    id: "tiger-hill",
    name: "Tiger Hill",
    category: "Hillstation",
    lat: 27.029,
    lon: 88.2655,
    city: "Darjeeling",
    images: ["/media/tiger-hill-sunrise.png"],
    description:
      "Famous sunrise viewpoint offering a panoramic view of Mount Kanchenjunga and Everest on clear days.",
    tips: ["Arrive early before sunrise", "Carry warm clothes"],
    entryFeeINR: "Free",
    hours: "04:00–18:00",
  },
  {
    id: "batasia-loop",
    name: "Batasia Loop",
    category: "Heritage",
    lat: 27.0165,
    lon: 88.2622,
    city: "Darjeeling",
    images: [
      "/media/Darjeeling-toy-train-in-Batasia-loop.jpg",
      "/media/bata.webp",
    ],
    description:
      "Iconic spiral railway loop with a war memorial and gardens, part of the UNESCO Darjeeling Himalayan Railway.",
    tips: ["Best when toy train passes", "Great photography spot"],
    entryFeeINR: 20,
    hours: "Sunrise–Sunset",
  },
  {
  id: "chowrasta-mall",
  name: "Chowrasta (The Mall)",
  category: "Cultural Site",
  lat: 27.036007,
  lon: 88.262675,
  city: "Darjeeling",
  images: ["/media/Darjeeling/chowrasta-1.jpg"],
  description:
    "Historic Victorian-era public square at the heart of Darjeeling, popular for leisurely strolls and local culture.",
  tips: ["Try pony rides", "Visit cafes & bookshops nearby"],
  entryFeeINR: "Free",
  hours: "Open all day",
},

{
  id: "observatory-hill-mahakal-temple",
  name: "Observatory Hill & Mahakal Temple",
  category: "Cultural Site",
  lat: 27.047718,
  lon: 88.268070,
  city: "Darjeeling",
  images: ["/media/Darjeeling/observatory-hill-1.jpg"],
  description:
    "Sacred hill with temple blending Hindu & Buddhist traditions; offers panoramic views above Chowrasta.",
  tips: ["Visit in evening for serenity", "Combine with a Mall Road walk"],
  entryFeeINR: "Free",
  hours: "6:00–20:00",
},

{
  id: "himalayan-mountaineering-institute",
  name: "Himalayan Mountaineering Institute (HMI)",
  category: "Pilgrimage",
  lat: 27.05873,
  lon: 88.25326,
  city: "Darjeeling",
  images: ["/media/Darjeeling/hmi-1.jpg"],
  description:
    "Premier mountaineering school and museum founded in 1954; training institute for climbers globally.",
  tips: ["Visit museum", "Check workshop timings; closed Thursdays"],
  entryFeeINR: 60,
  hours: "9:30–16:30 (Mon–Sat)",
},

{
  id: "darjeeling-zoological-park",
  name: "Padmaja Naidu Himalayan Zoological Park",
  category: "Wildlife",
  lat: 27.05861,
  lon: 88.25441,
  city: "Darjeeling",
  images: ["/media/Darjeeling/zoo-1.jpg"],
  description:
    "World’s highest-altitude zoo, conserving Himalayan fauna like snow leopards, red pandas, and Siberian tigers.",
  tips: ["Go early for active animals", "Closed Thursdays"],
  entryFeeINR: 60,
  hours: "8:30–16:00 (closed Thu)",
},

{
  id: "peace-pagoda",
  name: "Peace Pagoda (Japanese Temple)",
  category: "Temple",
  lat: 27.027587,
  lon: 88.258987,
  city: "Darjeeling",
  images: ["/media/Darjeeling/peace-pagoda-1.jpg"],
  description:
    "Serene white stupa dedicated to peace, located on Jalapahar hills near Nipponzan Myohoji Temple.",
  tips: ["Quiet spiritual spot", "Short drive from town center"],
  entryFeeINR: "Free",
  hours: "8:00–18:00",
},

{
  id: "batasia-loop",
  name: "Batasia Loop & Gorkha War Memorial",
  category: "Heritage",
  lat: 27.0418,
  lon: 88.2566,
  city: "Darjeeling",
  images: ["/media/Darjeeling/batasia-loop-1.jpg"],
  description:
    "Spiral rail loop of the Toy Train with landscaped gardens and war memorial, offering Himalayan vistas.",
  tips: ["Best lighting mid-morning", "Combine with toy train ride"],
  entryFeeINR: 30,
  hours: "6:00–18:00",
},

{
  id: "darjeeling-himalayan-railway",
  name: "Darjeeling Himalayan Railway (Toy Train)",
  category: "Heritage",
  lat: 27.0420,
  lon: 88.2636,
  city: "Darjeeling",
  images: ["/media/Darjeeling/toy-train-1.jpg"],
  description:
    "UNESCO World Heritage narrow-gauge railway (Toy Train) between NJP and Darjeeling, with zig-zags and loops.",
  tips: ["Book early—steam specials popular", "Board from NJP or Ghum"],
  entryFeeINR: "Varies",
  hours: "6:00–18:00",
},

{
  id: "bagdogra-airport",
  name: "Bagdogra Airport",
  category: "Transport",
  lat: 26.6812,
  lon: 88.3286,
  city: "Siliguri",
  images: ["/media/Transport/bagdogra-airport-1.jpg"],
  description:
    "Main airport serving Darjeeling and North Bengal, with good connectivity and transit options.",
  tips: ["Allow buffer time for uphill drive", "Prepaid taxis available outside"],
  entryFeeINR: "None",
  hours: "24 hours",
},

  // ===== Digha =====
  {
    id: "new-digha-beach",
    name: "New Digha Beach",
    category: "Beach",
    lat: 21.6266,
    lon: 87.5183,
    city: "Digha",
    images: ["/media/digha/digha-beach-bay-of-bengal.png"],
    description:
      "Popular beach destination in West Bengal with wide sandy shores, sunrise views, and seafood stalls.",
    tips: ["Avoid weekends for less crowd", "Best early morning"],
    entryFeeINR: "Free",
    hours: "Open all day",
  },

  // Birbhum District (central)
  {
    id: "birbhum-district",
    name: "Birbhum District (approx. center)",
    category: "Town",
    lat: 24.000000,
    lon: 87.583330,
    city: "Birbhum",
    images: [], // optional
    description: "Administrative district of West Bengal, known as the Land of Red Soil.",
    tips: [],
    entryFeeINR: "N/A",
    hours: "Open all day",
  },
  // Tarapith
  {
    id: "tarapith",
    name: "Tarapith Temple Town",
    category: "Pilgrimage",
    lat: 24.1100,
    lon: 87.8000,
    city: "Birbhum",
    images: [], // you can add images
    description:
      "Famous Tantric pilgrimage site dedicated to Maa Tara, known for the Tarapith Temple and Bamakhepa’s ashram at the cremation grounds.",
    tips: ["Respect local customs", "Best to visit early to avoid crowds"],
    entryFeeINR: "Free",
    hours: "All day",
  },
  {
    id: "visva-bharati",
    name: "Visva-Bharati University",
    category: "Heritage",
    lat: 23.6776,
    lon: 87.686,
    city: "Shantiniketan",
    images: ["/media/shantiniketan-university.png", "/media/santi.png"],
    description:
      "Founded by Rabindranath Tagore, it is a center of culture, arts, and education with historic significance.",
    tips: ["Check seasonal festivals", "Explore Tagore’s ashram nearby"],
    entryFeeINR: 30,
    hours: "10:00–17:00",
  },
  // ===== Places in Cooch Behar =====
  {
    id: "cooch-behar-palace",
    name: "Cooch Behar Palace",
    category: "Heritage",
    lat: 26.32694,
    lon: 89.43861,
    city: "Cooch Behar",
    images: ['/media/Cooch-behar/c-palace.jpg', '/media/Cooch-behar/COOCHBEHAR-3-1024x768-1.webp','/media/cooch-behar-palace.png'],
    description: "Elegant Italian Renaissance-style palace and museum, former royal residence of Koch dynasty.",
    tips: ["Best for photography", "Check museum timings"],
    entryFeeINR: "Varies",
    hours: "Typically 10:00–17:00",
  },
  {
    id: "madan-mohan-temple",
    name: "Madan Mohan Temple",
    category: "Temple",
    lat: 26.32024,
    lon: 89.44549,
    city: "Cooch Behar",
    images: ['media/Cooch-behar/madan-mohan-temple.jpg','/media/Cooch-behar/Madan_Mohan_Bari_Cooch_Behar.jpg'],
    description: "White temple dedicated to Lord Madan Mohan and other deities; center of Rash Yatra and Mela.",
    tips: ["Attend during Rash Yatra", "Moderate crowd post-festival"],
    entryFeeINR: "Free",
    hours: "All day",
  },
  {
    id: "baneswar-shiva-temple",
    name: "Baneswar Shiva Temple",
    category: "Temple",
    lat: 26.399063,
    lon: 89.497535,
    city: "Baneswar",
    images: ['/media/Cooch-behar/Baneshwar_Shiva_temple.jpg','/media/Cooch-behar/BS tempel.webp'],
    description: "Ancient Shiva temple with Shivalinga 10 ft below plinth and pond with tortoises (~10 km from city).",
    tips: ["“Maha Shivaratri is special", "Also visit the tortoise pond"],
    entryFeeINR: "Free",
    hours: "All day",
  },
  {
    id: "gosanimari-rajpat",
    name: "Gosanimari Rajpat",
    category: "Archaeological",
    lat: 26.032,
    lon: 89.484,
    city: "Gosanimari",
    images: ['/media/Cooch-behar/gosanimari.jpg','/media/Cooch-behar/gosa.jpg','/media/Cooch-behar/rajpat.jpg'],
    description: "Ruins of Kamatapur’s Rajpat fort, earthen walls and archaeological remains.",
    tips: ["Wear comfortable shoes", "Visit with guide if possible"],
    entryFeeINR: "Free",
    hours: "All day",
  },
  {
    id: "siddheswari-kali-bari",
    name: "Siddheswari Kali Bari",
    category: "Temple",
    lat: 26.32419, // estimated close to Cooch Behar center
    lon: 89.45100,
    city: "Cooch Behar",
    images: ['/media/Cooch-behar/ksp_8769-2.jpg','/media/Cooch-behar/kalibari.jpg'],
    description: "Temple built in 1830 by Maharaja Harendra Narayan dedicated to Goddess Siddheswari (~11 km from city).",
    tips: ["Combine with Baneswar visiting", "Peaceful atmosphere"],
    entryFeeINR: "Free",
    hours: "All day",
  },
  {
    id: "patlakhawa-forest",
    name: "Patlakhawa Forest",
    category: "Nature",
    lat: 26.4536,
    lon: 89.4725,
    images: ['/media/Cooch-behar/Patlakhawa Forest.jpeg','/media/Cooch-behar/palakkad.jpg'],
    city: "Patlakhawa",
    description: "Forest area home to elephants, deer, peacocks, and other wildlife.",
    entryFeeINR: "20",
    hours: "Sunrise – Sunset",
  },
  // ===== Dakshin Dinajpur =====
{
  id: "angina-bird-sanctuary",
  name: "Angina Bird Sanctuary",
  category: "Wildlife",
  lat: 25.30863,  // Approximate location near Tapan block and Kumarganj
  lon: 88.56644,  // :contentReference[oaicite:0]{index=0}
  city: "Kumarganj",
  images: ["/media/DakshinDinajpur/angina-1.jpg"],
  description:
    "Wetland habitat where over 100 species of migratory birds arrive in winter; excellent for bird watching and ecological tourism.",
  tips: ["Visit winter months for birdwatching", "Combine visit with Sarongbari picnic spot"],
  entryFeeINR: "Free",
  hours: "6:00–18:00",
},
{
  id: "tapan-dighi",
  name: "Tapan Dighi",
  category: "Nature",
  lat: 25.30056,  // 25°18'2\" N
  lon: 88.56944,  // 88°34'10\" E :contentReference[oaicite:1]{index=1}
  city: "Tapan",
  images: ["/media/DakshinDinajpur/tapan-dighi-1.jpg"],
  description:
    "Historic man-made lake and picnic spot in Tapan block; believed to be created by King Laxman Sen.",
  tips: ["Carry snacks and water", "Visit both Tapan Dighi and nearby archaeological mound"],
  entryFeeINR: "Free",
  hours: "6:00–18:00",
},
{
  id: "kaldighi-park",
  name: "Kaldighi Park",
  category: "Nature",
  lat: 25.396893,
  lon: 88.543333,
  city: "Gangarampur",
  images: ["/media/DakshinDinajpur/kaldighi-park-1.jpg"],
  description:
    "Public park surrounding a large lake; attracts migratory birds in winter and is ideal for family visits.",
  tips: ["Winter best for birdwatching", "Combine with visit to Dhal Dighi nearby"],
  entryFeeINR: "Free",
  hours: "10:00–18:00",
},
  // ===== Hooghly District =====
  {
    id: "bandel-church",
    name: "Basilica of the Holy Rosary (Bandel Church)",
    category: "Heritage",
    lat: 22.9191,
    lon: 88.3953,
    city: "Bandel",
    images: ["/media/Hooghly/bandel-church.jpg"],
    description:
      "One of the oldest Christian churches in Bengal, founded in 1599 and rebuilt in 1660, featuring Portuguese colonial architecture.",
    tips: ["Visit early to avoid crowds", "Observe the ship’s mast and ancient keystone"],
    entryFeeINR: "Free",
    hours: "10:00–17:00",
  },
  {
    id: "chandannagar-strand",
    name: "Chandannagar Strand",
    category: "Heritage",
    lat: 22.8568,
    lon: 88.3694,
    city: "Chandannagar",
    images: ["/media/Hooghly/chandannagar-strand.jpg"],
    description:
      "A nostalgic 2 km-long riverside promenade along the Hooghly River dating back to French colonial times.",
    tips: ["Walk during sunset for atmospheric views", "Explore nearby French heritage sites"],
    entryFeeINR: "Free",
    hours: "All day",
  },
  {
    id: "imambara",
    name: "Hooghly Imambara",
    category: "Heritage",
    lat: 22.8956,
    lon: 88.3907,
    city: "Hooghly",
    images: ["/media/Hooghly/imambara.jpg"],
    description:
      "Built in 1861 by Hazi Mohammad Mohsin, this grand mosque and madrasa complex is known for its massive clock tower and intricate architecture.",
    tips: ["Climb to the top for a panoramic river view", "Check the historic sundial"],
    entryFeeINR: "₹10",
    hours: "06:00–18:00",
  },
  {
    id: "rajeshwar-temple",
    name: "Raj Rajeshwar Temple",
    category: "Temple",
    lat: 22.8948,
    lon: 88.3963,
    city: "Hooghly",
    images: ["/media/Hooghly/rajeshwar-temple.jpg"],
    description:
      "An ancient Shiva temple in Hooghly, known for its terracotta artwork and cultural significance.",
    tips: ["Best visited during Shivratri", "Photography allowed outside"],
    entryFeeINR: "Free",
    hours: "06:00–20:00",
  },
  {
    id: "serampore-college",
    name: "Serampore College",
    category: "Heritage",
    lat: 22.7510,
    lon: 88.3422,
    city: "Serampore",
    images: ["/media/Hooghly/serampore-college.jpg"],
    description:
      "Established in 1818 by missionaries William Carey, Joshua Marshman, and William Ward, one of the oldest colleges in India.",
    tips: ["Explore colonial architecture", "Nearby Danish Tavern worth visiting"],
    entryFeeINR: "Free",
    hours: "All day",
  },

  // ===== Howrah District =====
  {
    id: "howrah-bridge",
    name: "Howrah Bridge (Rabindra Setu)",
    category: "Engineering",
    lat: 22.5900,
    lon: 88.3100,
    city: "Howrah",
    images: ["/media/Howrah/howrah-bridge.jpg"],
    description:
      "Iconic steel cantilever bridge over the Hooghly River, connecting Howrah and Kolkata, built in 1943.",
    tips: ["Visit at dawn or dusk for best lighting", "View it from the riverbank"],
    entryFeeINR: "Free",
    hours: "All day",
  },
  {
    id: "indian-botanical-garden",
    name: "Acharya Jagadish Chandra Bose Indian Botanical Garden",
    category: "Nature",
    lat: 22.5650,
    lon: 88.3450,
    city: "Shibpur (Howrah)",
    images: ["/media/Howrah/botanical-garden.jpg"],
    description:
      "Sprawling 109-hectare garden housing 12,000-plus plant species and the famous Great Banyan Tree.",
    tips: ["Ideal for morning walks", "Don’t miss the Great Banyan Tree"],
    entryFeeINR: "₹50",
    hours: "09:00–17:00",
  },
  {
    id: "gadiara",
    name: "Gadiara",
    category: "Nature",
    lat: 22.3288,
    lon: 87.9732,
    city: "Howrah",
    images: ["/media/Howrah/gadiara.jpg"],
    description:
      "Scenic spot where three rivers converge, known for Fort Mornington ruins and beautiful river cruises.",
    tips: ["Go for sunset cruise", "Bring picnic supplies"],
    entryFeeINR: "Free",
    hours: "All day",
  },
  {
    id: "santragachi-jheel",
    name: "Santragachi Jheel",
    category: "Lake",
    lat: 22.5895,
    lon: 88.2925,
    city: "Howrah",
    images: ["/media/Howrah/santragachi-jheel.jpg"],
    description:
      "Large lake attracting thousands of migratory birds, especially Siberian ducks and geese during winter.",
    tips: ["Best time November–February", "Carry binoculars for birdwatching"],
    entryFeeINR: "Free",
    hours: "All day",
  },
  {
    id: "avani-riverside-mall",
    name: "Avani Riverside Mall",
    category: "Market",
    lat: 22.5586,
    lon: 88.3047,
    city: "Howrah",
    images: ["/media/Howrah/avani-mall.jpg"],
    description:
      "Largest shopping mall in Howrah with retail stores, multiplex, and food court overlooking the Hooghly River.",
    tips: ["Good for family outing", "Try rooftop restaurants with river view"],
    entryFeeINR: "Free",
    hours: "10:30–22:00",
  },
  // ===== Jalpaiguri District =====
  {
    "id": "lataguri",
    "name": "Lataguri",
    "category": "Nature",
    "lat": 26.7667,
    "lon": 88.7333,
    "city": "Jalpaiguri",
    "images": ["/media/Jalpaiguri/lataguri.jpg"],
    "description": "Town in Dooars region known for wildlife and natural beauty, close to Gorumara National Park and Murti River.",
    "tips": ["Take jeep safari in Gorumara", "Explore local tea gardens"],
    "entryFeeINR": "Varies for safaris",
    "hours": "06:00–18:00"
  },
  {
    "id": "suntalekhola",
    "name": "Suntalekhola",
    "category": "Nature",
    "lat": 26.8500,
    "lon": 88.7000,
    "city": "Jalpaiguri",
    "images": ["/media/Jalpaiguri/suntalekhola.jpg"],
    "description": "Scenic offbeat village with lush green tea gardens, close to Neora Valley National Park.",
    "tips": ["Ideal for trekking and nature walks", "Carry picnic supplies"],
    "entryFeeINR": "Free",
    "hours": "All day"
  },
  {
    "id": "chalsa",
    "name": "Chalsa",
    "category": "Nature",
    "lat": 26.8333,
    "lon": 88.8000,
    "city": "Jalpaiguri",
    "images": ["/media/Jalpaiguri/chalsa.jpg"],
    "description": "Visually appealing town in Dooars known as the 'Queen of Dooars', surrounded by tea gardens.",
    "tips": ["Visit nearby tea estates", "Enjoy local cuisine in small eateries"],
    "entryFeeINR": "Free",
    "hours": "All day"
  },
  {
    "id": "bindu",
    "name": "Bindu",
    "category": "Nature",
    "lat": 26.7000,
    "lon": 88.9000,
    "city": "Jalpaiguri",
    "images": ["/media/Jalpaiguri/bindu.jpg"],
    "description": "Border town with Bhutan, offering scenic views of Bhutan hills and Jaldhaka River.",
    "tips": ["Great for photography", "Carry ID for border area"],
    "entryFeeINR": "Free",
    "hours": "All day"
  },
  {
    "id": "rocky-island",
    "name": "Rocky Island",
    "category": "Nature",
    "lat": 26.7800,
    "lon": 88.7200,
    "city": "Jalpaiguri",
    "images": ["/media/Jalpaiguri/rocky-island.jpg"],
    "description": "Popular spot for nature lovers offering stunning views of the surrounding landscape.",
    "tips": ["Best visited during sunrise or sunset", "Wear good trekking shoes"],
    "entryFeeINR": "Free",
    "hours": "All day"
  },
  {
    "id": "gorumara-national-park",
    "name": "Gorumara National Park",
    "category": "Wildlife",
    "lat": 26.7750,
    "lon": 88.7250,
    "city": "Jalpaiguri",
    "images": ["/media/Jalpaiguri/gorumara.jpg"],
    "description": "National park known for Indian rhinoceros, grasslands, and forests in Dooars.",
    "tips": ["Take a guided jungle safari", "Best visited early morning"],
    "entryFeeINR": "200–500",
    "hours": "06:00–16:00"
  },
  {
    "id": "chapramari-wildlife-sanctuary",
    "name": "Chapramari Wildlife Sanctuary",
    "category": "Wildlife",
    "lat": 26.8000,
    "lon": 88.7300,
    "city": "Jalpaiguri",
    "images": ["/media/Jalpaiguri/chapramari.jpg"],
    "description": "Sanctuary near Gorumara, known for elephants, Indian bison, deer, and a variety of birds.",
    "tips": ["Ideal for birdwatching", "Avoid loud noises in forest areas"],
    "entryFeeINR": "Varies for safari",
    "hours": "06:00–16:00"
  },
  {
    "id": "baikunthpur",
    "name": "Baikunthpur",
    "category": "Nature",
    "lat": 26.6500,
    "lon": 88.6500,
    "city": "Jalpaiguri",
    "images": ["/media/Jalpaiguri/baikunthpur.jpg"],
    "description": "Terai forest region between Mahananda and Teesta rivers, known for wildlife including elephants.",
    "tips": ["Carry insect repellent", "Visit during early morning for wildlife spotting"],
    "entryFeeINR": "Free",
    "hours": "All day"
  },
  {
    "id": "jhargram-rajbari",
    "name": "Jhargram Rajbari",
    "category": "Heritage",
    "lat": 22.4500,
    "lon": 86.9800,
    "city": "Jhargram",
    "images": ["/media/Jhargram/rajbari.jpg"],
    "description": "Italian-Islamic palace, residence of Malla Dev Royal family, partially converted to heritage homestay.",
    "tips": ["Book heritage rooms in advance", "Explore palace gardens"],
    "entryFeeINR": "Free",
    "hours": "09:00–18:00"
  },
  {
    "id": "savitri-temple",
    "name": "Savitri Temple",
    "category": "Religious",
    "lat": 22.4510,
    "lon": 86.9810,
    "city": "Jhargram",
    "images": ["/media/Jhargram/savitri-temple.jpg"],
    "description": "Temple of ancestral deity of Malla Dev dynasty, worshipped as Durga with rituals following Puranas.",
    "tips": ["Visit during Durga Puja for traditional rituals", "Respect local customs"],
    "entryFeeINR": "Free",
    "hours": "06:00–19:00"
  },
  {
    "id": "junglemahal-zoological-park",
    "name": "Junglemahal Zoological Park",
    "category": "Wildlife",
    "lat": 22.4400,
    "lon": 86.9700,
    "city": "Jhargram",
    "images": ["/media/Jhargram/junglemahal-zoo.jpg"],
    "description": "Zoo showcasing biodiversity of Lateritic Eco-System with mammals, birds, and reptiles.",
    "tips": ["Visit during morning hours", "Great for family outing"],
    "entryFeeINR": "50–100",
    "hours": "08:00–17:00"
  },
  {
    "id": "kendua-bird-spot",
    "name": "Kendua Migrating Birds",
    "category": "Nature",
    "lat": 22.4200,
    "lon": 86.9600,
    "city": "Jhargram",
    "images": ["/media/Jhargram/kendua.jpg"],
    "description": "Birding hotspot where migratory birds visit from May to November.",
    "tips": ["Carry binoculars", "Visit during early morning hours"],
    "entryFeeINR": "Free",
    "hours": "06:00–18:00"
  },
  {
    "id": "chilkigarh-sacred-grove",
    "name": "Chilkigarh Sacred Grove & Kanak Durga Temple",
    "category": "Religious",
    "lat": 22.4000,
    "lon": 86.9500,
    "city": "Jhargram",
    "images": ["/media/Jhargram/chilkigarh-grove.jpg"],
    "description": "Biodiversity heritage site with sacred grove and Kanak Durga Temple.",
    "tips": ["Respect sacred area rules", "Ideal for nature walks"],
    "entryFeeINR": "Free",
    "hours": "06:00–18:00"
  },
  {
    "id": "chilkigarh-raj-palace",
    "name": "Chilkigarh Raj Palace",
    "category": "Heritage",
    "lat": 22.3980,
    "lon": 86.9520,
    "city": "Jhargram",
    "images": ["/media/Jhargram/chilkigarh-palace.jpg"],
    "description": "Historic palace of Jamboni Zamindari estate, near Kanak Durga Temple.",
    "tips": ["Visit along with sacred grove", "Learn about local history"],
    "entryFeeINR": "Free",
    "hours": "09:00–18:00"
  },
  {
    "id": "amlachati-medicinal-garden",
    "name": "Medicinal Plants Garden",
    "category": "Nature",
    "lat": 22.4300,
    "lon": 86.9700,
    "city": "Jhargram",
    "images": ["/media/Jhargram/medicinal-garden.jpg"],
    "description": "Collection of 704 species of medicinal plants, maintained by the forest department.",
    "tips": ["Ideal for students and researchers", "Carry notebook for observations"],
    "entryFeeINR": "Free",
    "hours": "09:00–17:00"
  },
  {
    "id": "jhargram-eco-tourism-centre",
    "name": "Jhargram Eco-Tourism Centre & Tribal Museum",
    "category": "Nature",
    "lat": 22.4480,
    "lon": 86.9820,
    "city": "Jhargram",
    "images": ["/media/Jhargram/eco-tourism.jpg"],
    "description": "Forest retreat with tribal museum and folk performances, 2 km outside palace.",
    "tips": ["Attend weekend performances", "Try local cuisine"],
    "entryFeeINR": "50",
    "hours": "10:00–18:00"
  },
  {
    "id": "gurrasini-hill",
    "name": "Gurrasini Hill",
    "category": "Nature",
    "lat": 22.3600,
    "lon": 86.9400,
    "city": "Belpahari",
    "images": ["/media/Jhargram/gurrasini-hill.jpg"],
    "description": "Hill with Gurrasini Ashram for meditation and spiritual retreats.",
    "tips": ["Ideal for meditation", "Carry water and light snacks"],
    "entryFeeINR": "Free",
    "hours": "All day"
  },
  {
    "id": "khandarani-lake",
    "name": "Khandarani Lake",
    "category": "Nature",
    "lat": 22.3700,
    "lon": 86.9450,
    "city": "Belpahari",
    "images": ["/media/Jhargram/khandarani-lake.jpg"],
    "description": "Scenic lake surrounded by forests and mountains, home to migratory birds in winter.",
    "tips": ["Paddle boating available", "Ideal for photography"],
    "entryFeeINR": "Free",
    "hours": "06:00–17:00"
  },
  {
    "id": "ketki-spring",
    "name": "Spring of Ketki",
    "category": "Nature",
    "lat": 22.3500,
    "lon": 86.9300,
    "city": "Belpahari",
    "images": ["/media/Jhargram/ketki-spring.jpg"],
    "description": "Natural spring lake in Cherang hills with walking trails and pristine surroundings.",
    "tips": ["Wear comfortable shoes for trekking", "Carry water"],
    "entryFeeINR": "Free",
    "hours": "06:00–18:00"
  },
  {
    "id": "dhangikusum-falls",
    "name": "Dhangikusum & Dungri Falls",
    "category": "Nature",
    "lat": 22.3550,
    "lon": 86.9350,
    "city": "Belpahari",
    "images": ["/media/Jhargram/dhangikusum-falls.jpg"],
    "description": "Scenic waterfall with surrounding forest and trekking trails.",
    "tips": ["Best visited after monsoon", "Wear trekking shoes"],
    "entryFeeINR": "Free",
    "hours": "06:00–18:00"
  },
  {
    "id": "kankrajhore-forest",
    "name": "Kankrajhore Forest",
    "category": "Nature",
    "lat": 22.3400,
    "lon": 86.9200,
    "city": "Belpahari",
    "images": ["/media/Jhargram/kankrajhore-forest.jpg"],
    "description": "Verdant forest with mazy paths, hills, and tribal villages.",
    "tips": ["Ideal for trekking and tribal experiences", "Carry water and snacks"],
    "entryFeeINR": "Free",
    "hours": "06:00–18:00"
  },
  {
    "id": "laljal-cave",
    "name": "Laljal Cave",
    "category": "Heritage",
    "lat": 22.3450,
    "lon": 86.9150,
    "city": "Belpahari",
    "images": ["/media/Jhargram/laljal-cave.jpg"],
    "description": "Ancient cave and village with prehistoric remains and reddish spring water.",
    "tips": ["Carry torch and water", "Wear good shoes for trekking"],
    "entryFeeINR": "Free",
    "hours": "06:00–17:00"
  },
  {
    "id": "ghagra-river-rock",
    "name": "Ghagra River Rock",
    "category": "Nature",
    "lat": 22.3600,
    "lon": 86.9400,
    "city": "Belpahari",
    "images": ["/media/Jhargram/ghagra-river-rock.jpg"],
    "description": "Rocky pedestal on Ghagra river with gurgling streams, featured in Bengali film shooting.",
    "tips": ["Visit during monsoon for best view", "Ideal for photography"],
    "entryFeeINR": "Free",
    "hours": "06:00–18:00"
  },
  {
    "id": "tarafeni-dam",
    "name": "Tarafeni Dam",
    "category": "Nature",
    "lat": 22.3650,
    "lon": 86.9450,
    "city": "Belpahari",
    "images": ["/media/Jhargram/tarafeni-dam.jpg"],
    "description": "Dam on Tarafeni river with scenic rocky boulders, especially beautiful during surplus water release.",
    "tips": ["Visit during rainy season", "Carry camera for photography"],
    "entryFeeINR": "Free",
    "hours": "06:00–18:00"
  },
  {
    "id": "kanaisor-hill",
    "name": "Kanaisor Hill",
    "category": "Nature",
    "lat": 22.3700,
    "lon": 86.9500,
    "city": "Belpahari",
    "images": ["/media/Jhargram/kanaisor-hill.jpg"],
    "description": "Hill with annual Pahar Pujo festival and panoramic views of surrounding villages and forests.",
    "tips": ["Visit during festival for cultural experience", "Carry water and light snacks"],
    "entryFeeINR": "Free",
    "hours": "All day"
  },
  {
    "id": "chorchita-yogashram",
    "name": "Chorchita Yogashram & Choreshwar Shiv Mandir",
    "category": "Religious",
    "lat": 22.3800,
    "lon": 86.9600,
    "city": "Gopiballavpur",
    "images": ["/media/Jhargram/chorchita-yogashram.jpg"],
    "description": "Historic ashram and Shiv temple by Mahatma Shree Shree Swami Gobardhan Giri Maharaj near Subarnarekha river.",
    "tips": ["Ideal for meditation and spiritual retreat", "Respect ashram rules"],
    "entryFeeINR": "Free",
    "hours": "06:00–18:00"
  },
  {
    "id": "kuthighat",
    "name": "Kuthighat (Tourist Picnic Spot)",
    "category": "Nature",
    "lat": 22.3820,
    "lon": 86.9620,
    "city": "Gopiballavpur",
    "images": ["/media/Jhargram/kuthighat.jpg"],
    "description": "Riverbank tourist spot along Rantua river, ideal for picnics.",
    "tips": ["Bring picnic supplies", "Visit during morning or evening"],
    "entryFeeINR": "Free",
    "hours": "06:00–18:00"
  },
  {
    "id": "rameshwar-temple",
    "name": "Rameshwar Temple",
    "category": "Heritage",
    "lat": 22.3900,
    "lon": 86.9700,
    "city": "Gopiballavpur",
    "images": ["/media/Jhargram/rameshwar-temple.jpg"],
    "description": "Historic Shiv temple established by Lord Rama, with ancient stone pillars.",
    "tips": ["Visit early morning for serene experience", "Respect temple customs"],
    "entryFeeINR": "Free",
    "hours": "05:00–20:00"
  },




];

// ===== All Hotels in West Bengal =====
export const HOTELS: Hotel[] = [
  // Kolkata
  {
    id: "taj-bengal",
    name: "Taj Bengal",
    lat: 22.5404,
    lon: 88.345,
    rating: 4.7,
    priceBand: "Premium",
    nearPlaceId: "victoria-memorial",
    city: "Kolkata",
  },
  {
    id: "park-kolkata",
    name: "The Park Kolkata",
    lat: 22.5535,
    lon: 88.3528,
    rating: 4.3,
    priceBand: "Mid",
    nearPlaceId: "victoria-memorial",
    city: "Kolkata",
  },

  // Sundarbans (none yet)

  // Alipurduar
  {
    id: 'jayanti-resort',
    name: 'Jayanti River View Lodge',
    lat: 26.6165,
    lon: 89.6001,
    rating: 4.1,
    priceBand: 'Budget',
    nearPlaceId: 'jayanti',
    city: 'Jayanti'
  },
  {
    id: 'chilapata-lodge',
    name: 'Mendabari Jungle Camp',
    lat: 26.5790,
    lon: 89.4040,
    rating: 4.4,
    priceBand: 'Mid',
    nearPlaceId: 'chilapata',
    city: 'Chilapata'
  },
  {
    id: 'raimatang-eco',
    name: 'Raimatang Eco Stay',
    lat: 26.6125,
    lon: 89.6730,
    rating: 4.0,
    priceBand: 'Budget',
    nearPlaceId: 'raimatang',
    city: 'Raimatang'
  },
  {
    id: 'jaigaon-inn',
    name: 'Hotel Druk Jaigaon',
    lat: 26.8465,
    lon: 89.3742,
    rating: 4.2,
    priceBand: 'Mid',
    nearPlaceId: 'jaigaon',
    city: 'Jaigaon'
  },
  {
    id: 'totopara-camp',
    name: 'Totopara Tribal Homestay',
    lat: 26.8335,
    lon: 89.3635,
    rating: 4.3,
    priceBand: 'Budget',
    nearPlaceId: 'totopara',
    city: 'Totopara'
  },
  {
    id: 'rajabhatkhawa-hotel',
    name: 'Rajabhatkhawa Forest Lodge',
    lat: 26.6150,
    lon: 89.5470,
    rating: 4.1,
    priceBand: 'Budget',
    nearPlaceId: 'rajabhatkhawa',
    city: 'Rajabhatkhawa'
  },
  {
    id: 'buxa-lodge',
    name: 'Buxa Jungle Lodge',
    lat: 26.6280,
    lon: 89.5650,
    rating: 4.5,
    priceBand: 'Mid',
    nearPlaceId: 'buxa-tiger-reserve',
    city: 'Buxa'
  },
  {
    id: 'jaldapara-safari',
    name: 'Jaldapara Safari Lodge',
    lat: 26.6890,
    lon: 89.2770,
    rating: 4.6,
    priceBand: 'Premium',
    nearPlaceId: 'jaldapara',
    city: 'Madarihat'
  },

  // Bankura
  {
    id: 'green-palace-guest',
    name: 'Green Palace Guest House',
    lat: 23.2375,
    lon: 87.0719,
    rating: 4.8,
    priceBand: 'Budget',
    nearPlaceId: 'susunia-hill',
    city: 'Bankura'
  },
  {
    id: 'maa-laxmi-lodge',
    name: 'Hotel O Maa Laxmi Lodge',
    lat: 23.2324,
    lon: 87.0782,
    rating: 3.4,
    priceBand: 'Budget',
    nearPlaceId: 'susunia-hill',
    city: 'Bankura'
  },
  {
    id: 'anticlock-resort',
    name: 'Anticlock Suites & Resort',
    lat: 23.2850,
    lon: 87.0610,
    rating: 4.5,
    priceBand: 'Premium',
    nearPlaceId: 'susunia-hill',
    city: 'Bankura'
  },
  {
    id: 'hotel-olivia',
    name: 'Hotel Olivia and Resort',
    lat: 23.0659,
    lon: 87.3214,
    rating: 3.7,
    priceBand: 'Mid',
    nearPlaceId: 'bishnupur-terracotta',
    city: 'Bishnupur'
  },
  {
    id: 'hotel-annapurna',
    name: 'Hotel Annapurna Bishnupur',
    lat: 23.0732,
    lon: 87.3220,
    rating: 4.0,
    priceBand: 'Budget',
    nearPlaceId: 'bishnupur-terracotta',
    city: 'Bishnupur'
  },
  {
    id: 'monalisa-lodge',
    name: 'Monalisa Lodge Bishnupur',
    lat: 23.0739,
    lon: 87.3232,
    rating: 3.9,
    priceBand: 'Budget',
    nearPlaceId: 'bishnupur-terracotta',
    city: 'Bishnupur'
  },
  {
    id: 'sonar-bangla-joypur',
    name: 'Hotel Sonar Bangla Joypur Forest',
    lat: 23.0545,
    lon: 87.3060,
    rating: 4.2,
    priceBand: 'Mid',
    nearPlaceId: 'bishnupur-terracotta',
    city: 'Bishnupur'
  },
  {
    id: "bishnupur-guest",
    name: "Bishnupur Heritage Stay",
    lat: 23.072,
    lon: 87.324,
    rating: 4.2,
    priceBand: "Budget",
    nearPlaceId: "bishnupur-terracotta",
    city: "Bishnupur"
  },

  // Darjeeling
  {
    id: "mayfair-darjeeling",
    name: "Mayfair Darjeeling",
    lat: 27.0418,
    lon: 88.2627,
    rating: 4.6,
    priceBand: "Premium",
    nearPlaceId: "tiger-hill",
    city: "Darjeeling",
  },
  
  // Hotels near Tiger Hill
  {
    id: "mount-lungta-boutique",
    name: "Mount Lungta Boutique Hotel & Spa",
    lat: 27.0290, // Approx Darjeeling area (close to Tiger Hill)
    lon: 88.2655,
    rating: 4.5,
    priceBand: "Mid",
    nearPlaceId: "tiger-hill",
    city: "Darjeeling",
  },
  {
    id: "orion-retreat",
    name: "Orion Retreat",
    lat: 27.0280,
    lon: 88.2660,
    rating: 4.0,
    priceBand: "Budget",
    nearPlaceId: "tiger-hill",
    city: "Darjeeling",
  },
  {
    id: "udan-himalayan-suites-spa",
    name: "Udaan Himalayan Suites and Spa",
    lat: 27.0275,
    lon: 88.2670,
    rating: 4.6,
    priceBand: "Premium",
    nearPlaceId: "tiger-hill",
    city: "Darjeeling",
  },

  // Hotels near Batasia Loop
  {
    id: "mayfair-hill-resort",
    name: "MAYFAIR Hill Resort",
    lat: 27.0410,
    lon: 88.2560,
    rating: 4.7,
    priceBand: "Premium",
    nearPlaceId: "batasia-loop",
    city: "Darjeeling",
  },
  {
    id: "the-elgin-darjeeling",
    name: "The Elgin, Darjeeling",
    lat: 27.0390,
    lon: 88.2590,
    rating: 4.8,
    priceBand: "Premium",
    nearPlaceId: "batasia-loop",
    city: "Darjeeling",
  },
  {
    id: "ramada-gandhi-road",
    name: "Ramada by Wyndham Darjeeling (Gandhi Road)",
    lat: 27.0385,
    lon: 88.2605,
    rating: 4.3,
    priceBand: "Mid",
    nearPlaceId: "batasia-loop",
    city: "Darjeeling",
  },
  {
    id: "istana-resort-spa",
    name: "Istana Resort & Spa",
    lat: 27.0395,
    lon: 88.2575,
    rating: 4.5,
    priceBand: "Premium",
    nearPlaceId: "batasia-loop",
    city: "Darjeeling",
  },

  // Hotel near Peace Pagoda for illustration
  {
    id: "hotel-basera",
    name: "Hotel Basera",
    lat: 27.0295,
    lon: 88.2590,
    rating: 4.0,
    priceBand: "Mid",
    nearPlaceId: "peace-pagoda",
    city: "Darjeeling",
  },


  

  // Digha
  {
    id: "sea-hawk-digha",
    name: "Hotel Sea Hawk",
    lat: 21.627,
    lon: 87.519,
    rating: 4.2,
    priceBand: "Mid",
    nearPlaceId: "new-digha-beach",
    city: "Digha",
  },

  // Shantiniketan

  {
    id: "camellia-resort",
    name: "Camellia Resort Shantiniketan",
    lat: 23.678,
    lon: 87.689,
    rating: 4.3,
    priceBand: "Mid",
    nearPlaceId: "visva-bharati",
    city: "Shantiniketan",
  },
  {
    id: "tarapith-inn",
  name: "Hotel Tara Inn",
    lat: 24.1090, // approximate
    lon: 87.8010,
     rating: 4.0,
    priceBand: "Budget",
    nearPlaceId: "tarapith",
    city: "Tarapith",
   },
   {
    id: "sonar-bangla-tarapith",
    name: "Hotel Sonar Bangla – Tarapith",
    lat: 24.1085,
    lon: 87.7975,
    rating: 3.9,
    priceBand: "Mid",
    nearPlaceId: "tarapith",
    city: "Tarapith",
  },
  {
    id: "rajdeep-guest-house",
    name: "Rajdeep Guest House",
    lat: 24.1090,
    lon: 87.7980,
    rating: 4.2,
    priceBand: "Budget",
    nearPlaceId: "tarapith",
    city: "Tarapith",
  },
  {
    id: "hotel-royal-city",
    name: "Hotel Royal City",
    lat: 26.3230,
    lon: 89.4490,
    rating: 3.1,
    priceBand: "Budget",
    nearPlaceId: "cooch-behar-palace",
    city: "Cooch Behar",
  },
  {
    id: "hotel-heritage-kanta",
    name: "Kanta Heritage Hotel",
    lat: 26.3245,
    lon: 89.4515,
    rating: 3.5,
    priceBand: "Mid",
    nearPlaceId: "cooch-behar-palace",
    city: "Cooch Behar",
  },
  {
    id: "hotel-debdutta",
    name: "Hotel Debdutta",
    lat: 26.3250,
    lon: 89.4520,
    rating: 3.5,
    priceBand: "Mid",
    nearPlaceId: "cooch-behar-palace",
    city: "Cooch Behar",
  },
  {
    id: "hotel-akash-ganga",
    name: "Hotel Akash Ganga",
    lat: 26.3255,
    lon: 89.4530,
    rating: 3.8,
    priceBand: "Mid",
    nearPlaceId: "cooch-behar-palace",
    city: "Cooch Behar",
  },
  {
    id: "capital-residency",
    name: "Capital Residency",
    lat: 26.3260,
    lon: 89.4505,
    rating: 3.9,
    priceBand: "Mid",
    nearPlaceId: "cooch-behar-palace",
    city: "Cooch Behar",
  },
  {
    id: "hotel-mayur",
    name: "Hotel Mayur",
    lat: 26.3280,
    lon: 89.4480,
    rating: 3.2,
    priceBand: "Mid",
    nearPlaceId: "new-cooch-behar-station",
    city: "Cooch Behar",
  },
  {
    id: "hotel-jonaki-restaurant",
    name: "Hotel Jonaki & Family Restaurant",
    lat: 26.3275,
    lon: 89.4475,
    rating: 3.7,
    priceBand: "Budget",
    nearPlaceId: "new-cooch-behar-station",
    city: "Cooch Behar",
  },
  {
    id: "maharani-palace",
    name: "Maharani Palace",
    lat: 26.3270,
    lon: 89.4495,
    rating: 1.9,
    priceBand: "Budget",
    nearPlaceId: "new-cooch-behar-station",
    city: "Cooch Behar",
  },

  // Rural areas of the district
  {
    id: "baneswar-area-stay",
    name: "Baneswar Area Hotel",
    lat: 26.3990,
    lon: 89.4975,
    rating: 4.0, // estimated
    priceBand: "Budget",
    nearPlaceId: "baneswar-shiva-temple",
    city: "Baneswar",
  },
  {
    id: "shree-jee-emporium",
    name: "Shree Jee Emporium",
    lat: 26.3242,
    lon: 89.4508,
    rating: 4.0,
    priceBand: "Mid",
    nearPlaceId: "cooch-behar-palace",
    city: "Cooch Behar",
  },
  {
    id: "tripti-hotel",
    name: "Tripti Hotel",
    lat: 26.3240,
    lon: 89.4510,
    rating: 3.5,
    priceBand: "Budget",
    nearPlaceId: "cooch-behar-palace",
    city: "Cooch Behar",
  },
  {
    id: "white-house-hotel",
    name: "White House Hotel",
    lat: 26.3238,
    lon: 89.4512,
    rating: 3.0,
    priceBand: "Budget",
    nearPlaceId: "cooch-behar-palace",
    city: "Cooch Behar",
  },
  {
    id: "yuvraj-hotel",
    name: "Yuvraj Hotel",
    lat: 26.3235,
    lon: 89.4515,
    rating: 3.5,
    priceBand: "Budget",
    nearPlaceId: "cooch-behar-palace",
    city: "Cooch Behar",
  },
  
  // Hotels near Angina Bird Sanctuary & Tapan Dighi (Gangarampur area)
  {
    id: "hotel-delite-gangarampur",
    name: "Hotel Delite",
    lat: 25.3980, // Approximate location in Gangarampur
    lon: 88.5400,
    rating: 4.0,
    priceBand: "Budget",
    nearPlaceId: "angina-bird-sanctuary",
    city: "Gangarampur",
  },
  {
    id: "akash-residency-gangarampur",
    name: "Hotel Akash Residency",
    lat: 25.3975,
    lon: 88.5410,
    rating: 3.8,
    priceBand: "Budget",
    nearPlaceId: "tapan-dighi",
    city: "Gangarampur",
  },
  {
    id: "swastiloke-utsav-bhawan",
    name: "Swastiloke Utsav Bhawan",
    lat: 25.3985,
    lon: 88.5420,
    rating: 4.4,
    priceBand: "Mid",
    nearPlaceId: "kaldighi-park",
    city: "Gangarampur",
  },

  // Hotels near Balurghat (district HQ, relevant for access)
  {
    id: "hotel-lila-balurghat",
    name: "The Hotel Lila",
    lat: 25.2165,
    lon: 88.8040,
    rating: 4.0,
    priceBand: "Budget",
    nearPlaceId: "balurghat-railway-station",
    city: "Balurghat",
  },
  {
    id: "kokoro-farmhouse",
    name: "Balurghat Hotel Kokoro Farmhouse",
    lat: 25.2170,
    lon: 88.8050,
    rating: 4.3,
    priceBand: "Mid",
    nearPlaceId: "balurghat-railway-station",
    city: "Balurghat",
  },
  {
    id: "royal-inn-balurghat",
    name: "The Royal Inn Hotels and Banquet",
    lat: 25.2150,
    lon: 88.8060,
    rating: 4.2,
    priceBand: "Mid",
    nearPlaceId: "balurghat-railway-station",
    city: "Balurghat",
  },
  
  // Hotels near Bandel Church (Bandel, Hooghly)
  {
    "id": "avenue-plaza-hotel",
    "name": "Avenue Plaza Hotel and Restaurant",
    "lat": 22.9000,
    "lon": 88.3900,
    "rating": 4.2,
    "priceBand": "Mid",
    "nearPlaceId": "bandel-church",
    "city": "Shrirampur"
  },
  {
    "id": "hotel-red-velvet",
    "name": "Hotel Red Velvet",
    "lat": 22.9274,
    "lon": 88.3773,
    "rating": 4.0,
    "priceBand": "Budget",
    "nearPlaceId": "bandel-church",
    "city": "Bandel"
  },

  // Hotels near Chandannagar Strand (Chandannagar, Hooghly)
  {
    "id": "deteeex-hotel-ivy",
    "name": "Deteex Hotel Ivy",
    "lat": 22.8648,
    "lon": 88.3633,
    "rating": 3.8,
    "priceBand": "Budget",
    "nearPlaceId": "chandannagar-strand",
    "city": "Chandannagar"
  },
  {
    "id": "swetas-home-stay-new",
    "name": "Sweta's Home Stay (New)",
    "lat": 22.8648,
    "lon": 88.3633,
    "rating": 4.4,
    "priceBand": "Budget",
    "nearPlaceId": "chandannagar-strand",
    "city": "Chandannagar"
  },
  {
    "id": "stay-inn-hotel-restaurant",
    "name": "Stay Inn Hotel and Restaurant",
    "lat": 22.8648,
    "lon": 88.3633,
    "rating": 4.0,
    "priceBand": "Budget",
    "nearPlaceId": "chandannagar-strand",
    "city": "Chandannagar"
  },
  {
    "id": "shivam-home-stay",
    "name": "Shivam Home Stay",
    "lat": 22.8648,
    "lon": 88.3633,
    "rating": 4.0,
    "priceBand": "Budget",
    "nearPlaceId": "chandannagar-strand",
    "city": "Chandannagar"
  },
  {
    "id": "gharana-resort",
    "name": "Gharana Resort",
    "lat": 22.8648,
    "lon": 88.3633,
    "rating": 4.5,
    "priceBand": "Mid",
    "nearPlaceId": "chandannagar-strand",
    "city": "Chandannagar"
  },

  // Hotels near Bandel Junction Railway Station (Chinsurah side)
  {
    "id": "hotel-plaza-chinsurah",
    "name": "Hotel Plaza",
    "lat": 22.9000,
    "lon": 88.3900,
    "rating": 3.9,
    "priceBand": "Budget",
    "nearPlaceId": "bandel-church",
    "city": "Chinsurah"
  },
  {
    "id": "kings-crown-hotel",
    "name": "King's Crown Hotel",
    "lat": 22.9000,
    "lon": 88.3900,
    "rating": 4.8,
    "priceBand": "Mid",
    "nearPlaceId": "bandel-church",
    "city": "Chinsurah"
  },
  {
    "id": "anushka-garden-resort",
    "name": "Anushka Garden & Resort",
    "lat": 22.9000,
    "lon": 88.3900,
    "rating": 4.1,
    "priceBand": "Budget",
    "nearPlaceId": "bandel-church",
    "city": "Chinsurah"
  },
  {
    "id": "surya-hotel-chinsurah",
    "name": "Surya Hotel",
    "lat": 22.9000,
    "lon": 88.3900,
    "rating": 4.5,
    "priceBand": "Budget",
    "nearPlaceId": "bandel-church",
    "city": "Chinsurah"
  },

  // Hotels near Howrah Bridge / Howrah Railway Station
  {
    "id": "the-lalit-great-eastern",
    "name": "The Lalit Great Eastern Kolkata",
    "lat": 22.5684,
    "lon": 88.3496,
    "rating": 4.6,
    "priceBand": "Premium",
    "nearPlaceId": "howrah-bridge",
    "city": "Kolkata"
  },
  {
    "id": "peerless-inn-kolkata",
    "name": "The Peerless Inn Kolkata",
    "lat": 22.5684,
    "lon": 88.3496,
    "rating": 4.2,
    "priceBand": "Mid",
    "nearPlaceId": "howrah-bridge",
    "city": "Kolkata"
  },
  {
    "id": "hotel-howrah",
    "name": "Hotel Howrah",
    "lat": 22.5726,
    "lon": 88.3639,
    "rating": 3.8,
    "priceBand": "Budget",
    "nearPlaceId": "howrah-railway-station",
    "city": "Howrah"
  },
  {
    "id": "sapphire-suites",
    "name": "Sapphire Suites",
    "lat": 22.5726,
    "lon": 88.3639,
    "rating": 4.1,
    "priceBand": "Mid",
    "nearPlaceId": "howrah-railway-station",
    "city": "Kolkata"
  },
  {
    "id": "floatel-kolkata",
    "name": "Floatel - A Floating Hotel",
    "lat": 22.5726,
    "lon": 88.3639,
    "rating": 4.0,
    "priceBand": "Premium",
    "nearPlaceId": "howrah-bridge",
    "city": "Kolkata"
  },
 {
    "id": "sinclairs-retreat-dooars",
    "name": "Sinclairs Retreat Dooars",
    "lat": 26.7720,
    "lon": 88.7350,
    "rating": 4.5,
    "priceBand": "Premium",
    "nearPlaceId": "lataguri",
    "city": "Jalpaiguri"
  },
  {
    "id": "dreamland-lataguri",
    "name": "Dreamland Lataguri",
    "lat": 26.7675,
    "lon": 88.7340,
    "rating": 4.2,
    "priceBand": "Mid",
    "nearPlaceId": "lataguri",
    "city": "Jalpaiguri"
  },
  {
    "id": "green-forest-resort",
    "name": "Green Forest Resort",
    "lat": 26.7660,
    "lon": 88.7325,
    "rating": 4.3,
    "priceBand": "Mid",
    "nearPlaceId": "lataguri",
    "city": "Jalpaiguri"
  },
  {
    "id": "bon-holong-resort",
    "name": "Bon Holong Resort",
    "lat": 26.8510,
    "lon": 88.7010,
    "rating": 4.2,
    "priceBand": "Mid",
    "nearPlaceId": "suntalekhola",
    "city": "Jalpaiguri"
  },
  {
    "id": "gorumara-cottage-resort",
    "name": "Gorumara Cottage Resort",
    "lat": 26.7760,
    "lon": 88.7245,
    "rating": 4.4,
    "priceBand": "Mid",
    "nearPlaceId": "gorumara-national-park",
    "city": "Jalpaiguri"
  },
  {
    "id": "chapramari-eco-lodge",
    "name": "Chapramari Eco Lodge",
    "lat": 26.7990,
    "lon": 88.7315,
    "rating": 4.3,
    "priceBand": "Mid",
    "nearPlaceId": "chapramari-wildlife-sanctuary",
    "city": "Jalpaiguri"
  },
  {
    "id": "chalsa-tea-estate-resort",
    "name": "Chalsa Tea Estate Resort",
    "lat": 26.8340,
    "lon": 88.8020,
    "rating": 4.1,
    "priceBand": "Mid",
    "nearPlaceId": "chalsa",
    "city": "Jalpaiguri"
  },
  {
    "id": "bindu-riverside-resort",
    "name": "Bindu Riverside Resort",
    "lat": 26.7010,
    "lon": 88.9015,
    "rating": 4.0,
    "priceBand": "Mid",
    "nearPlaceId": "bindu",
    "city": "Jalpaiguri"
  },
  {
    "id": "rocky-island-resort",
    "name": "Rocky Island Resort",
    "lat": 26.7815,
    "lon": 88.7210,
    "rating": 4.3,
    "priceBand": "Mid",
    "nearPlaceId": "rocky-island",
    "city": "Jalpaiguri"
  },
  {
    "id": "baikunthpur-jungle-lodge",
    "name": "Baikunthpur Jungle Lodge",
    "lat": 26.6510,
    "lon": 88.6515,
    "rating": 4.2,
    "priceBand": "Mid",
    "nearPlaceId": "baikunthpur",
    "city": "Jalpaiguri"
  },


  {
    "id": "jhargram-raj-palace",
    "name": "Jhargram Raj Palace",
    "lat": 22.4569,
    "lon": 86.9863,
    "rating": 4.2,
    "priceBand": "Premium",
    "nearPlaceId": "jhargram-raj-palace",
    "city": "Jhargram"
  },
  {
    "id": "hotel-white-house-lodge",
    "name": "Hotel White House Lodge",
    "lat": 22.4569,
    "lon": 86.9863,
    "rating": 4.0,
    "priceBand": "Budget",
    "nearPlaceId": "jhargram-raj-palace",
    "city": "Jhargram"
  },
  {
    "id": "vintage-plaza",
    "name": "The Vintage Plaza",
    "lat": 22.4569,
    "lon": 86.9863,
    "rating": 4.1,
    "priceBand": "Budget",
    "nearPlaceId": "jhargram-raj-palace",
    "city": "Jhargram"
  }




  
];