name: Android CI/CD

on:
  push:
    branches:
      - MyChoice   # or main/develop branch
  pull_request:
    branches:
      - MyChoice

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'   # adjust if needed

    - name: Install dependencies
      run: npm ci



    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Make Gradle wrapper executable
      run: chmod +x ./android/gradlew

    - name: Build Android APK
      run: ./gradlew assembleRelease
      working-directory: ./android

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: WBTour-Android-APK
        path: android/app/build/outputs/apk/release/app-release.apk
