name: iOS-swift-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Swift Build
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Xcode (latest version on GitHub macOS runners)
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      # Install CocoaPods if your project uses it
      - name: Install dependencies
        run: |
          cd ios
          pod install --repo-update || true

      # Build .app file
      - name: Build app
        run: |
          xcodebuild \
            -workspace ios/YourApp.xcworkspace \ # change if using workspace
            -scheme YourApp \
            -sdk iphoneos \
            -configuration Release \
            build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      # Package into .ipa
      - name: Create IPA
        run: |
          mkdir -p Payload
          cp -R build/Release-iphoneos/YourApp.app Payload/
          zip -r YourApp.ipa Payload

      # Upload IPA to GitHub Release
      - name: Upload IPA to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: WBtour.ipa
          tag: v1.0
          overwrite: true
          body: "First Swift iOS release"
